# Generated by Django 6.0.6 on 2026-06-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('vote_cast', 'Vote Cast'), ('election_created', 'Election Created'), ('applications_opened', 'Applications Opened'), ('applications_closed', 'Applications Closed'), ('voting_opened', 'Voting Opened'), ('voting_closed', 'Voting Closed'), ('candidate_approved', 'Candidate Approved'), ('candidate_rejected', 'Candidate Rejected'), ('results_published', 'Results Published')], max_length=50),
        ),
        migrations.AlterField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('applications_open', 'Applications Open'), ('applications_closed', 'Applications Closed'), ('voting_open', 'Voting Open'), ('voting_closed', 'Voting Closed'), ('results', 'Results Published')], default='draft', max_length=30),
        ),
    ]
